version: 2.1
setup: true
orbs:
  orb-tools: circleci/orb-tools@11.6
  shellcheck: circleci/shellcheck@3.1

tags_and_branches: &tags_and_branches
  tags:
    only: /^(major|minor|patch)-release-v\d+\.\d+\.\d+$/

only_branches: &only_branches
  branches:
    only: /.*/

workflows:
  lint-pack-publish-dev:
    jobs:
      - orb-tools/lint:
            filters: *tags_and_branches

      - orb-tools/pack:
          filters: *tags_and_branches

      - orb-tools/review:
          filters: *tags_and_branches

      - shellcheck/check:
          filters: *tags_and_branches

      - orb-tools/publish:
          name: publish-dev
          orb-name: financial-times/golang-ci
          pub-type: dev
          vcs-type: << pipeline.project.type >>
          context: cm-team-orb-publishing
          enable-pr-comment: false
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - orb-tools/review
            - shellcheck/check
          filters: *tags_and_branches

      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          context: cm-team-orb-publishing
          requires:
            - publish-dev
          filters: *only_branches
