version: 2.1

orbs:
  orb-tools: circleci/orb-tools@9.0.1
  golang-ci: financial-times/golang-ci@<<pipeline.parameters.dev-orb-version>>

tags_and_branches: &tags_and_branches
  tags:
    only: /^(major|minor|patch)-release-v\d+\.\d+\.\d+$/

only_tags: &only_tags
  branches:
    ignore: /.*/
  tags:
    only: /^(major|minor|patch)-release-v\d+\.\d+\.\d+$/

only_branches: &only_branches
  branches:
    only: /.*/

only_master: &only_master
  branches:
    only:
      - master

parameters:
  dev-orb-version:
    default: dev:alpha
    type: string
  run-integration-tests:
    default: false
    type: boolean

workflows:
  lint_publish-dev_prod-release:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint:
          filters: *tags_and_branches

      - orb-tools/pack:
          requires:
            - orb-tools/lint
          filters: *tags_and_branches

      - orb-tools/publish-dev:
          orb-name: financial-times/golang-ci
          context: cm-team-orb-publishing
          requires:
            - orb-tools/pack
          filters: *tags_and_branches

      - orb-tools/trigger-integration-tests-workflow:
          context: cm-team-orb-publishing
          requires:
            - orb-tools/publish-dev
          filters: *only_branches

      # This step is executed only on tag release. Please note that currently CircleCI is not able to execute
      # the integration-tests workflow on tag release. So dev-promote-prod-from-git-tag job is not in the same
      # workflow as the integration tests.
      - orb-tools/dev-promote-prod-from-git-tag:
          orb-name: financial-times/golang-ci
          context: cm-team-orb-publishing
          add-pr-comment: false
          perform-branch-check: true
          requires:
            - orb-tools/publish-dev
          filters: *only_tags

  # The integration tests should be run in a separate workflow triggered by the one above so that they use
  # the latest dev:alpha version of the orb that was released by the publish-dev job above.
  integration-tests:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - golang-ci/build-and-test:
          name: integration-tests-default
          filters: *only_branches

      - golang-ci/build-and-test:
          name: integration-tests-with-neo4j
          executor-name: golang-ci/default-with-neo4j
          filters: *only_branches

      - golang-ci/build-and-test:
          name: integration-tests-with-elasticsearch
          executor-name: golang-ci/default-with-elasticsearch
          filters: *only_branches

      - golang-ci/build-and-test:
          name: integration-tests-with-mysql
          executor-name: golang-ci/default-with-mysql
          filters: *only_branches

      - golang-ci/build-and-test:
          name: integration-tests-with-postgres
          executor-name: golang-ci/default-with-postgres
          filters: *only_branches

      - golang-ci/docker-build:
          name: docker-job-integration-tests
          filters: *only_branches

  # Republish the dev:alpha orb every two months to ensure new pipelines don't get rejected due to expired dev orbs.
  # We need to refer to the dev release of the orb for the integration-tests workflow. However when there is no dev orb
  # release (or it's expired) this config file is marked as invalid and none of its workflows is allowed to run.
  keep-dev-orb-alive:
    triggers:
      - schedule:
          cron: "0 0 1 1,3,5,7,9,11 *"
          filters: *only_master
    jobs:
      - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: financial-times/golang-ci
          context: cm-team-orb-publishing
          requires:
            - orb-tools/pack
