description: >
  Builds source code using go modules, doesn't modify the go mod file
parameters:
  github-username:
    description: >
      username of user with access to private github repositories
    type: env_var_name
    default: GITHUB_USERNAME
  github-token:
    description: >
      token to for the user with access to private github repositories
    type: env_var_name
    default: GITHUB_TOKEN
steps:
  - run:
      name: Set git ssh
      command: >
        git config --global --unset url."ssh://git@github.com".insteadOf
  - run:
      name: Set GOPRIVATE
      command: export GOPRIVATE="github.com/Financial-Times"
  - run:
      name: Set git username/token
      command:
        "git config --global url.\"https://${<<parameters.github-username>>}:\
        ${<<parameters.github-token>>}@github.com\".insteadOf \
        \"https://github.com\""
  - run:
      name: Build source
      command: go build -mod=readonly -v ./...
