description: Builds source code using go modules, doesn't modify the go mod file
parameters:
  github-username:
    description: username of user with access to private github repositories
    type: env_var_name
    default: GITHUB_USERNAME
  github-token:
    description: token to for the user with access to private github repositories
    type: env_var_name
    default: GITHUB_TOKEN
steps:
  - run:
      name: Build source code
      command: |
        SSH_INSTEAD_OF=$(git config --global --get url."ssh://git@github.com".insteadOf)
        if [ -n "$SSH_INSTEAD_OF" ]; then
          echo "Exists!"
          git config --global --unset url."ssh://git@github.com".insteadOf
        fi
        export GOPRIVATE="github.com/Financial-Times"
        git config --global url."https://${<<parameters.github-username>>}:${<<parameters.github-token>>}@github.com".insteadOf "https://github.com"
        go build -mod=readonly -v ./...
