description: >
  Builds source code using go modules, doesn't modify the go mod file
parameters:
  github-username:
    description: >
      username of user with access to private github repositories
    type: env_var_name
    default: GITHUB_USERNAME
  github-token:
    description: >
      token for the user with access to private github repositories
    type: env_var_name
    default: GITHUB_TOKEN

steps:
  - run:
      name: Set env vars from GITHUB_USERNAME
      command: >
        export GITHUB_USERNAME=${<<parameters.github-username>>}
  - run:
      name: Set env vars from GITHUB_TOKEN
      command: >
        export GITHUB_TOKEN=${<<parameters.github-token>>}
  - run:
      name: Build Source
      command: <<include(scripts/build-source.sh)>>
