parameters:
  file-path:
    description: Path to the configuration file
    type: string
    default: ./api/api.yml
  executor-name:
    description: Executor for this job
    type: executor
    default: node

executor: <<parameters.executor-name>>

steps:
  - checkout
  - run:
      name: Validate openapi file
      environment:
        FILE_PATH: <<parameters.file-path>>
      command: <<include(scripts/openapi-validate.sh)>>
