description: >
    This executor is based on a machine executor with Docker and
    Docker Compose pre-installed, and installs Golang.
parameters:
  golang-version:
    type: string
    default: "1.24.2"
  github-username:
    type: env_var_name
    default: GITHUB_USERNAME
  github-token:
    type: env_var_name
    default: GITHUB_TOKEN
  golang-image-version:
    type: string
    default: "1"
  coverage-report-folder:
    type: string
    default: /tmp/coverage-results/coverage
docker:
  - image: cimg/go:<<parameters.golang-version>>
    auth:
      username: $DOCKERHUB_USERNAME
      password: $DOCKERHUB_ACCESS_TOKEN
environment:
  EXECUTOR_NAME: compose-executor
