description: >
  This executor is based on golang Docker image.
parameters:
  golang-image-version:
    type: string
    default: "1"
docker:
  - image: golang:<<parameters.golang-image-version>>
    auth:
      username: $DOCKERHUB_USERNAME
      password: $DOCKERHUB_ACCESS_TOKEN
