version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gocognit
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unparam
    - unused
    - whitespace
  settings:
    gocognit:
      min-complexity: 20
    govet:
      enable:
        - shadow
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    revive:
      confidence: 0
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        text: weak cryptographic primitive
    paths:
      - test/testdata_etc
      - pkg/golinters/goanalysis/(checker|passes)
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - test/testdata_etc
      - pkg/golinters/goanalysis/(checker|passes)
